import React from 'react'

// Statically adding SEO related data
/*export const metadata = {
  title: "Posts",
  description: "Generated by create next app",
};*/

// Dynamically adding SEO related data
/*export async function generateMetadata({params, searchParams}) {
  const product = await getProduct(params.id);
  return {
    title: product.title
  }
}*/

const page = () => {
  return (
    <div>
      POSTS
    </div>
  )
}

export default page;