import React from 'react'

export const metadata = {
  title: "Posts",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      POSTS
    </div>
  )
}

export default page;